name: Test Redhat-compatible platforms

on:
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Platforms'
        default: '["centos:7", "quay.io/centos/centos:stream8", "quay.io/centos/centos:stream9",
                   "rockylinux:8", "rockylinux:9",
                   "oraclelinux:7", "oraclelinux:8", "oraclelinux:9",
                   "amazonlinux:2", "amazonlinux:2022", "amazonlinux:2023",
                   "fedora:latest"]'

jobs:
  redhat-compat-matrix:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l -eo pipefail {0}
    strategy:
      matrix:
        os: ${{ fromJson(inputs.platforms) }}
      fail-fast: false
    container:
      image: ${{ matrix.os }}
      options: --cpus 2
    steps:
    - name: Prerequisites
      run: |
        yum install -y tar gzip
    - uses: actions/checkout@v3
      with:
        submodules: false
#    - run: |
#        git config --global --add safe.directory '*'
#        # git submodule update --init --recursive
    - name: Python
      run: |
        ./bin/getpy3
    - name: Setup repositories
      run: |
        V=1 ./bin/getepel
    - name: Installations
      run: |
        ./bin/getgcc --modern
    - name: Verify
      run: |
        python3 --version
        python3 -m pip list -v
        echo "System gcc: $(/usr/bin/gcc --version | head -1)"
        echo "gcc: $(gcc --version | head -1)"
        echo "glibc: $(./bin/glibcver)"
        echo "libstdc++: $(./bin/libstdc++ver)"
